name:  Deploy

on:
  push:
    branches: [ master ]

env:
  LANG: C.UTF-8

jobs:
  runhaskell:
    name: Build and test 
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: freckle/stack-cache-action@main
      # - uses: freckle/stack-action@v5
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: 9.8.1 
          enable-stack: true
          stack-version: "latest"
      - run: make prepare-rust-interop
      - run: stack --no-terminal build --dependencies-only

      # - run: stack install --local-bin-path=. --ghc-options '-optl-static -fPIC'
      - run: stack install --local-bin-path=. 
      # - run: stack test

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
